#pragma once

#ifdef _WIN32
#define ALTBASE_UTXO_IMPORT extern "C" __declspec(dllimport)
#define ALTBASE_UTXO_CALL __cdecl
#else
#define ALTBASE_UTXO_IMPORT extern "C"
#define ALTBASE_UTXO_CALL
#endif

#define ALTBASE_DECLARE_UTXO_WALLET(name) \
  ALTBASE_UTXO_IMPORT char* ALTBASE_UTXO_CALL altbase_##name##_wallet_request(const char* request); \
  ALTBASE_UTXO_IMPORT void ALTBASE_UTXO_CALL altbase_##name##_wallet_free(char* value)

ALTBASE_DECLARE_UTXO_WALLET(bitcoin2);
ALTBASE_DECLARE_UTXO_WALLET(bitcoin);
ALTBASE_DECLARE_UTXO_WALLET(bitcoincashii);
ALTBASE_DECLARE_UTXO_WALLET(firo);
ALTBASE_DECLARE_UTXO_WALLET(btgs);
ALTBASE_DECLARE_UTXO_WALLET(capstash);
ALTBASE_DECLARE_UTXO_WALLET(hypercoin);
ALTBASE_DECLARE_UTXO_WALLET(mydogecoin);
ALTBASE_DECLARE_UTXO_WALLET(pepecoin);
ALTBASE_DECLARE_UTXO_WALLET(kerrigan);
ALTBASE_DECLARE_UTXO_WALLET(scash);
ALTBASE_DECLARE_UTXO_WALLET(litecoinii);
ALTBASE_DECLARE_UTXO_WALLET(neoxa);
ALTBASE_DECLARE_UTXO_WALLET(terracoin);
ALTBASE_DECLARE_UTXO_WALLET(junkcoin);
ALTBASE_DECLARE_UTXO_WALLET(raptoreum);
ALTBASE_DECLARE_UTXO_WALLET(pearl);

#undef ALTBASE_DECLARE_UTXO_WALLET
#undef ALTBASE_UTXO_IMPORT
#undef ALTBASE_UTXO_CALL
